
import React, { useState, useEffect, useCallback } from 'react';
// Fix: Added .tsx extensions to component imports to resolve module loading errors.
import WelcomeScreen from './components/WelcomeScreen.tsx';
import LoadingScreen from './components/LoadingScreen.tsx';
import SimulationDashboard from './components/SimulationDashboard.tsx';
import { generateWorldElements } from './services/geminiService.ts';
import { SimulationState, Agent, Gender, GameEvent, GameEventType } from './types.ts';
import { generateMarkovName } from './services/markovService.ts';
import { assetLoader } from './assets.ts';

type AppPhase = 'welcome' | 'genesis' | 'simulation' | 'error';

const generateInitialAgents = (count: number): Agent[] => {
  const agents: Agent[] = [];
  for (let i = 0; i < count; i++) {
    const gender: Gender = Math.random() > 0.5 ? 'male' : 'female';
    agents.push({
      id: `agent-${i}`,
      name: generateMarkovName(gender),
      gender: gender,
      x: 50, // Starting position
      y: 50,
      sprite: gender === 'male' ? 'colonist_male_1' : 'colonist_female_1',
      state: 'idle',
      state_timer: Math.random() * 100,
      destination: null,
      path: null,
      task: null,
      health: { current: 100, max: 100 },
      morale: { current: Math.floor(Math.random() * 20) + 50, max: 100 }, // Morale awal antara 50-70
      energy: { current: Math.floor(Math.random() * 40) + 60, max: 100 }, // Energi awal antara 60-100
    });
  }
  return agents;
};

const App: React.FC = () => {
  const [phase, setPhase] = useState<AppPhase>('welcome');
  const [initialState, setInitialState] = useState<SimulationState | null>(null);
  const [isFadingOut, setIsFadingOut] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleBegin = () => {
    setPhase('genesis');
  };

  const startSimulation = useCallback(async () => {
    try {
      await assetLoader.loadAssets();
      const worldElements = await generateWorldElements();

      const initialAgents = generateInitialAgents(5);
      const genesisEvent: GameEvent = {
        id: `event-${Date.now()}`,
        timestamp: 0,
        type: GameEventType.NARRATIVE,
        title: "The Awakening",
        description: "A small group of survivors emerge from the dust, their pasts a blur, their future an unwritten page in the scorched book of this new world.",
        isAiGenerated: true,
      };

      const state: SimulationState = {
        tick: 0,
        isPaused: false,
        agents: initialAgents,
        resources: { food: 50, wood: 20, scrap: 10, stability: 75, researchPoints: 0 },
        events: [genesisEvent],
        world: {
            width: 100,
            height: 100,
            tileMap: [], // Will be generated by worker
            resourceNodes: [], // Will be generated by worker
            lootContainers: [], // Will be generated by worker
            placedStructures: [],
            biomes: worldElements.biomes.map((b, i) => ({ ...b, id: `biome-${i}` })),
            structures: worldElements.structures.map((s, i) => ({ ...s, id: `structure-${i}` })),
            creatures: worldElements.creatures.map((c, i) => ({ ...c, id: `creature-${i}` })),
        },
        culturalValues: {
            collectivism: 50,
            pragmatism: 50,
            spirituality: 50,
        },
        completedResearchIds: [],
        knownBlueprintIds: ['shelter_1'], // Start with basic shelter knowledge
        activeResearchId: null,
      };

      setInitialState(state);

      // Fade out the loading screen before showing the simulation
      setIsFadingOut(true);
      setTimeout(() => {
        setPhase('simulation');
      }, 500); // Match duration of fade-out animation

    } catch (err) {
      console.error("Genesis failed:", err);
      setError("Failed to generate the world. The AI might be resting. Please try again later.");
      setPhase('error');
    }
  }, []);

  useEffect(() => {
    if (phase === 'genesis') {
      startSimulation();
    }
  }, [phase, startSimulation]);

  if (phase === 'welcome') {
    return <WelcomeScreen onBegin={handleBegin} />;
  }
  
  if (phase === 'genesis') {
    return <LoadingScreen isFadingOut={isFadingOut} />;
  }

  if (phase === 'simulation' && initialState) {
    return <SimulationDashboard initialState={initialState} />;
  }
  
  if (phase === 'error') {
      return (
          <div className="flex flex-col items-center justify-center h-screen bg-slate-900 text-white">
              <h1 className="text-3xl text-red-500 font-bold">An Error Occurred</h1>
              <p className="mt-4 text-slate-300">{error}</p>
          </div>
      )
  }

  return null; // Should not be reached
};

export default App;
